### ISSUE TITLE
Export parseRequestParams similar to express-graphql

### ISSUE THREAD

**Issue by ritvick** [graphql/graphql-http#106]
### Story

As a _user

I want parseRequestParams function to be exported

So that same implementation can be used outside the package when interacting with graphql-http. 
This was the behaviour in express-graphql implementation.

### Acceptance criteria

- _user I can access parseRequestParams  from graphql-http package.

**Comment by enisdenjo** [comment]
Interesting request, I'll see what I can do. Thanks!

**Comment by ritvick** [comment]
Hi @enisdenjo 
I have created a PR here: https://github.com/graphql/graphql-http/pull/110

**Comment by enisdenjo** [comment]
There was more than just exporting the core parser. I've created an improved PR in #111. Thanks for you help though, hope you don't mind!

Nevertheless, a new version will be published soon. Thank you for your patiance.

**Comment by ritvick** [comment]
Thanks for all the help @enisdenjo
