### ISSUE TITLE
When checking the Accept header the charset is expected to be utf8 not utf-8

### ISSUE THREAD

**Issue by pkqk** [graphql/graphql-http#120]
**Expected Behaviour**
A request with the HTTP header:
```
Accept: application/json; charset=utf-8
```
is accepted as a GraphQL request

**Actual Behaviour**
The request is rejected with:
```
HTTP 406 Not Acceptable
```

**Debug Information**
I think the check here is wrong and should be looking for `utf-8` not `utf8`.
https://github.com/graphql/graphql-http/blob/v1.22.0/src/handler.ts#L593

**Comment by enisdenjo** [comment]
Thank you for bringing this up! A new version is out with a fix.
