### ISSUE TITLE
Change schema at runtime ? 

### ISSUE THREAD

**Issue by jhay06** [graphql/graphql-http#122]
Hi would like to request or if it existing please add to documentation 

Please add the option to change schema at runtime , 

in python and flask with ariadne this is possible , 

should have different schema per URL , yes i know i can define the schema and the URL before the express server runs but the thing is , everytime i have to add new schema i need to define another URL with its own createHandler option , 

i just want to add a folder directory then inside off every folder created there is api.js that defines the rootValue methods , and its own schema ,  the goal is to everytime we have another API we will add new folder and an api.js file and it will be accessible via url http://mydomain.com/partner/code   , this code is dynamic so i only need to use this express js routing app.use('/partner/:code') to make my code accessible via request.params  and this code will be equal to the partner folder where api and schemas reside  

thank you

**Comment by jhay06** [comment]
okay got the resolution here no need to comment back thank you

**Comment by jhay06** [comment]
okay its just a simple as instead of using createHandler as a parameter i just used it as callback , i think it is really a callback  

app.use("/my/path/:code", (req,res)=>{ 
    var code = req.params.code; 
   var schema = require('./path/'+code+'/schema.graphql');
   var api = require('./path/'+code+'/api.js') 
   createHandler({ schema:schema, rootValue: api() })(req,res) ;
});

**Comment by enisdenjo** [comment]
You're creating brand new handlers for each request. Instead, I'd recommend using the [`schema` property, 
 hwich is also a function](https://github.com/graphql/graphql-http/blob/main/docs/interfaces/handler.HandlerOptions.md#schema) where you can perform your schema discovery.

**Comment by NCVIDevASD** [comment]
> You're creating brand new handlers for each request. Instead, I'd recommend using the [`schema` property, hwich is also a function](https://github.com/graphql/graphql-http/blob/main/docs/interfaces/handler.HandlerOptions.md#schema) where you can perform your schema discovery.

please show how to do it to make it dynamically , thanks
