### ISSUE TITLE
v1.22.2 has breaking change with the strictness of "onOperation" for what is a valid answer

### ISSUE THREAD

**Issue by jeremiewtd** [graphql/graphql-http#133]
Using `v1.22.1`, returning this value from the `onOperation` handler works well but now doesn't work anymore using the `v1.22.2` : 

```js
return [
  JSON.stringify(result),
  {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=utf-8',
    },
  },
];
```

Looking at the code in this [PR](https://github.com/graphql/graphql-http/pull/127), this should be the source of the changes, the validation of type of `statusText` introduces a breaking change of the interpretation of what is returned by `onOperation`.

The example above doesn't work anymore, maybe this code is not suitable from the beginning but with `v1.22.1` it worked.

**Expected Behaviour**
The given response still works or else the library should have change its major version.

**Actual Behaviour**
The given response is not interpreted as a valid response anymore.

**Further Information**
A bit surprising that this change (and others) are not included in the changelog for this release.

**Comment by enisdenjo** [comment]
Thanks for pointing this out, this was an oversight on my end. Both `status` and `statusText` are actually optional ([see here](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response#options)).

I'll roll out a fix soon!
