### ISSUE TITLE
Error: The GraphQL schema is not provided (Express)

### ISSUE THREAD

**Issue by amerikan** [graphql/graphql-http#14]
**Screenshot**

**Expected Behaviour**

I followed the recipe from https://github.com/graphql/graphql-http#recipes for migration from `express-graphql`. When I run the server I would expect it to work as with express-graphql (no errors).

**Actual Behaviour**

When starting the server I get:

```
0|www    | Internal error occurred during request handling. Please check your implementation. Error: The GraphQL schema is not provided
0|www    |     at handler (/Users/e/Desktop/projects/my/node_modules/graphql-http/lib/handler.js:202:23)
0|www    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|www    |     at async requestListener (/Users/e/Desktop/projects/my/node_modules/graphql-http/lib/use/express.js:28:34)
```

**Debug Information**
Help us debug the bug?

**Further Information**

Using:

- `graphql-http 1.7.0`
- `@graphql-tools/schema 9.0.4` to create my schema (is this not supported?)

**Comment by enisdenjo** [comment]
Hey thanks for reporting. Can you please share your server implementation code? Are you sure you're providing a schema?

**Comment by amerikan** [comment]
@enisdenjo noticed that I was using a callback with `express-graphql` and it had been working. However, that way it doesn't work with `graphql-http` since it's not a valid argument.

```js
graphqlHTTP((req) => ({
    schema,
  }))
```

```js
graphqlHTTP({
    schema,
  })
```
At least now I know what's the problem.

**Comment by chongma** [comment]
I am also migrating from `express-graphql` but I have been using the callback.  How do I keep it?

**Comment by amerikan** [comment]
@chongma, not sure, I just ended up migrating to Yoga GrahpQL which wasn't too bad: https://the-guild.dev/graphql/yoga-server/docs/migration/migration-from-express-graphql

**Comment by chongma** [comment]
It seems to work like this
```javascript
router.use(path,
        middleware,
        (req, res) => {
            const handler = createHandler({
                schema,
                context: {
                    loaders: createLoaders(),
                    user,
                    ipaddress: req.ip
                },
                customFormatErrorFn: function (err) {
                    // this should catch any unhandled errors from the resolvers
                    console.error(err)
                }
            })
            handler(req, res)
        }
```
The trouble I am having now is whether `customFormatErrorFn` will work as expected

**Comment by chongma** [comment]
i guess it is using the `formatError` function now https://github.com/graphql/graphql-http/blob/main/docs/modules/handler.md#formaterror
