### ISSUE TITLE
Allow to configure the rootValue

### ISSUE THREAD

**Issue by Mogztter** [graphql/graphql-http#30]
### Story

As a _user_ migrating from `express-graphql`, I want to pass a `rootValue` resolver. With `express-graphql`, I was able to do the following: 

```js
app.get('/graphql', graphqlHTTP((req, res) => ({
  schema,
  rootValue: resolvers
})))
```

Ideally, I would like to set `rootValue` as an option of `createHandler`

```js
app.use(
  '/graphql',
  createHandler({ schema,  rootValue }),
)
```

### Acceptance criteria

- _user_ is able to configure a `rootValue` without overriding the whole `ExecutionContext` with `onSubscribe`
- _user_ can find documentation on how to configure a `rootValue`

### Note

Maybe using a `rootValue` is not recommended anymore? Maybe there's an alternative? For reference, here's how I declare my schema/resolvers:

```js
module.exports = {
  /**
   * Create an article.
   */
  articles: async (args, { req }) => {
    // ...
  }
  /**
   * Delete an article.
   */
  deleteArticle: async (args, { req }) => {
    // ...
  },
}
```

```js
const gql = require('graphql-tag')
const { buildASTSchema } = require('graphql')

module.exports = buildASTSchema(gql`
  type Article {
    _id: ID!
    title: String
    content: String
    createdAt: String
    updatedAt: String
  }

  type RootQuery {
    articles (user: ID): [Article!]!
  }

  type RootMutation {
    deleteArticle(article: ID!): Article!
  }

  schema {
    query: RootQuery
    mutation: RootMutation
  }
`)
```

**Comment by enisdenjo** [comment]
This makes sense! Thank you for opening an issue, I will tackle this rather soon.

**Comment by manishbhatt94** [comment]
@enisdenjo There isn't much documentation available on how to use rootValue.

Like in the samples shared in the issue's description by this issue's author, we get access to query arguments and the request object as the 1st & 2nd parameters of each resolver defined via rootValue in express-graphql.

But in graphql-http, that isn't the case, I think, since graphql-http when calling the resolvers passed undefined as the 2nd argument instead of `{ req }`.

**Comment by manishbhatt94** [comment]
Hey, I figured out how it works.. you need to use the `context` option in `createHandler` (which has access to the request) and then return whatever you want, and that would be passed as the 2nd argument when the library calls the resolvers. Sorry for posting the earlier comment, but the thing is the documentation is kinda not straightforward in the sense of its not mentioned anywhere with what arguments will resolvers defined under rootValue be called with.
