### ISSUE TITLE
Response containing errors parsing variables is nested twice

### ISSUE THREAD

**Issue by schwma** [graphql/graphql-http#40]
**Screenshot**
<img width="899" alt="Screenshot 2023-01-18 at 13 28 46" src="https://user-images.githubusercontent.com/37244550/213173359-1bbe141c-3212-4c5b-87a4-1b66e1473cce.png">

**Expected Behaviour**
I expected the error response to be structured like this:
```json
{
    "errors": [
        {
            "locations": [
                {
                    "column": 8,
                    "line": 1
                }
            ],
            "message": "Variable \"$input\" got invalid value \"foo\"; Int cannot represent non-integer value: \"foo\""
        }
    ]
}
```

**Actual Behaviour**
but instead it was nested twice like so:
```json
{
    "errors": [
        {
            "errors": [
                {
                    "locations": [
                        {
                            "column": 8,
                            "line": 1
                        }
                    ],
                    "message": "Variable \"$input\" got invalid value \"foo\"; Int cannot represent non-integer value: \"foo\""
                }
            ]
        }
    ]
}
```

**Debug Information**
Minimal example to reproduce:

Code:
```js
const { GraphQLSchema, GraphQLObjectType, GraphQLInt } = require("graphql");

const express = require("express");
const { createHandler } = require("graphql-http/lib/use/express");

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "Query",
    fields: {
      hello: {
        type: GraphQLInt,
        args: {
          input: {
            type: GraphQLInt,
          },
        },
      },
    },
  }),
});

const app = express();
app.all("/graphql", createHandler({ schema }));

app.listen({ port: 4000 });
console.log("Listening to port 4000");
```

Send a query such as:
```gql
query ($input: Int) {
  hello(input: $input)
}
```
with variables:
```json
{ "input": "foo" }
```

At first glance after briefly debugging it appears as though the error is [here in the `makeResponse` function](https://github.com/graphql/graphql-http/blob/8716392aea82c961effde77f0b590d6b72268536/src/handler.ts#L702-L706).

**Further Information**
The nesting format shown above under the "Expected Behaviour" section is the response that is returned by other GraphQL server frameworks such as `express-graphql` and `graphql-yoga`. Other errors returned by `graphql-http` are also not nested twice, such as when sending the following query against the example above.

Query
```gql
{
  hello(input: "foo")
}
```

Response:
```json
{
    "errors": [
        {
            "locations": [
                {
                    "column": 16,
                    "line": 1
                }
            ],
            "message": "Int cannot represent non-integer value: \"foo\""
        }
    ]
}
```

**Comment by enisdenjo** [comment]
hey @schwma thank you for reporting this, IDK how we've missed this! A fix will be released soon.

**Comment by schwma** [comment]
Great, thanks for the fast fix and release!
