### ISSUE TITLE
Missing variable coercion failure audit

### ISSUE THREAD

**Issue by trevor-scheer** [graphql/graphql-http#57]
I'm looking for an audit that enforces:
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#variable-coercion-failure
...but I'm not finding one. Is this missing, and would you be interested in a PR to add it?

Spotted by @glasser

**Comment by enisdenjo** [comment]
Great spot, thanks! PRs are always welcome. 😄
