### ISSUE TITLE
Add to the context values the response of the route, because it is usefull for set cookies for example.

### ISSUE THREAD

**Issue by aleleba** [graphql/graphql-http#66]
### Story

As a _user or client or server_

I want _some feature_

I want to add to the context values the response of the route, because it is usefull for set cookies for example.

So that _some value_

I want to add to the context values the response of the route, because it is usefull for set cookies for example.

### Acceptance criteria

Something like this:
```
createHandler({
  schema,
  context: (req, res, params) => ({ req, res, params })
})
```

**Comment by enisdenjo** [comment]
hey hey, sorry for the delay. I already have something in the pipe for this! will be pushed tomorrow

**Comment by aleleba** [comment]
@enisdenjo thank you!, if you need help, it sholud be a pleasure to help 👍🏼

**Comment by enisdenjo** [comment]
This is now live with [v1.17.0](https://github.com/graphql/graphql-http/releases/tag/v1.17.0), example usage with `express` would roughly be (very similar for all other node-style handlers too):

```js
import express from 'express'; // yarn add express
import { createHandler } from 'graphql-http/lib/use/express';
import { schema } from './my-graphql-schema';

const app = express();
app.all(
  '/graphql',
  createHandler({
    schema,
    context(req) {
      req.context.res.setHeader('x-my-header', 'my-value');
      return undefined;
    },
  }),
);

app.listen({ port: 4000 });
console.log('Listening to port 4000');
```

**Comment by aleleba** [comment]
Thank you @enisdenjo, I tried and worked 👍🏼
