### ISSUE TITLE
Support for graphiql

### ISSUE THREAD

**Issue by destroyer22719** [graphql/graphql-http#82]
I was looking forward to starting to learn graphql and migrate from rest for my a personal project. Every other tutorial in the realm of NodeJS and Express recommend to use `express-graph` but it is deprecated and this module is recommend. However, I noticed one feature seems to be missing, `graphiql`. This isn't a dealbreaker but it would be nice to have this feature in `graphql-http`.

**Comment by raulfdm** [comment]
+1

**Comment by enisdenjo** [comment]
Duplicate of #38.
